### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by cwensley** [philstopford/etoViewport#24]
Hey @philstopford, I have some things I'd like to discuss regarding this project.  I know in the past you have said it would be no problem for me to bring it into the "officially supported" fold, and that's what I'd like to do.  Namely, the following:

- [x] Fork the repo to the picoe organization
- [x] Rename the project and assemblies to Eto.OpenTK.* (since it only works with OpenTK)
- [x] Upgrade projects to sdk-style
- [ ] Add Eto.Gtk platform
- [x] Add nuget packages
- [x] Add CI builds
- [x] Add a process where adding a tag will build an official version and publish to nuget

What are your thoughts?  Would you like to keep the official repo here, or does this sound okay to you?  I'm also open to other ideas if you or anyone else has any.

**Comment by philstopford** [comment]
I'm OK with all of that. I don't have any issues with someone else taking this over (especially since others did most of the hard work anyway).

However, honestly, I'd rather see the Eto.Veldrid effort being taken as a baseline (assuming Rob is happy with this idea), as it covers multiple backends (Vulkan, Direct*, OpenGL, metal). I'm still fighting to understand how to draw multiple entities (in my fork of Rob's effort), but I think this would be more future-proof and attractive than the OpenTK-only approach.

**Comment by cwensley** [comment]
Hey @philstopford, awesome thanks.

I agree that  Eto.Veldrid would be a better toolkit to support going forward because of the multiple backends, and I can foresee doing the same with that project as well (assuming all involved would like that).  However, etoViewport is in use for some commercial projects that I'm involved in and making updates more accessible (nuget, etc) would help greatly.  

I'm not too familiar with Veldrid's api, is it similar and/or compatible with OpenTK's?  If so then we can certainly retire this project, otherwise it may be beneficial to keep this one around for those that have existing OpenTK code.

**Comment by ItEndsWithTens** [comment]
Just wanted to chime in and say that on a personal level, I'm more than happy to contribute as much or as little from Eto.Veldrid as is useful. Take anything that's not nailed down!

On a practical/technical level, however, I'd urge extreme caution. Veldrid makes Metal, Vulkan, and D3D 11 easy enough to embed in a GUI framework like Eto, but OpenGL (and I assume OpenGLES, too, which it also supports) is a bit prickly. Users are expected to provide the so-called "platform info", including things like a means of retrieving GL function pointers. The examples all use SDL2 as a means of getting up and running, and it provides things like GetProcAddress out of the box. Embedding SDL2 windows in Eto is something I initially researched, but if it's even possible it's well beyond me.

What I ended up doing was building atop etoViewport (now rebranded Eto.OpenTK, for any future readers), and OpenTK, by--and I cannot stress this enough--

**accessing private members of certain OpenTK classes**.

I currently only grab [the OpenTK.Platform.Utilities.CreateGetAddress method](https://github.com/ItEndsWithTens/Eto.Veldrid/blob/1f3d70dfe289ca18462095e8f16ad9a18858d398/src/Eto.VeldridSurface/VeldridSurface.cs#L48) and [the GraphicsContext.available_contexts field](https://github.com/ItEndsWithTens/Eto.Veldrid/blob/1f3d70dfe289ca18462095e8f16ad9a18858d398/src/Eto.VeldridSurface/VeldridSurface.cs#L58), but they're both private.

I know; I'm as disgusted with myself as you are. Naturally, since they're not part of a public API, there's no guarantee of them staying where they are between different OpenTK versions, so it's not something I'd expect is shippable in a production environment. For my silly little toy application, that will see handfuls of users when it's done if it sees any at all, I felt safe, but I can't say the same for others.

The only alternatives I could think of were finding an OpenGL wrapper for C# that offered GetProcAddress and the like, or embedding an SDL2-created window in Eto. I wasn't able to find any examples of the former, especially none as mature as OpenTK, and the latter saw me beat my head against my keyboard for about a week before giving in.

That's the biggest reason I haven't turned Eto.Veldrid into an actual library, instead leaving it a simple test project, but if that can be surmounted, I'd love to see it happen.

As far as Veldrid's API, its focus is on what I understand is the more modern style of graphics coding (please do take my lack of experience into account when judging my opinions), moving away from the state machine convention. For my [Quake .map viewer](https://github.com/ItEndsWithTens/Arbatel) I'm currently maintaining two rendering paths, [one using straight OpenTK](https://github.com/ItEndsWithTens/Arbatel/blob/beb545f0e456231eda9e9d59941d1310c1e2b4ce/src/Arbatel.Core/Graphics/OpenGLBackEnd.cs) and [the other with Veldrid](https://github.com/ItEndsWithTens/Arbatel/blob/beb545f0e456231eda9e9d59941d1310c1e2b4ce/src/Arbatel.Core/Graphics/VeldridBackEnd.cs). Not the work of the next Carmack or Abrash, but both written by the same person, at the same skill level, so maybe they'll give an inkling of the comparison.

I maintain the two different backends since as I understand it, Veldrid's OpenGL support starts at 3.0, even though I have code and shaders that work fine with 2.0 as long as certain extensions are present. I have an old laptop I like to use that doesn't support 3.0 and I desperately wanted my stuff to run there. :D If you want to run just pure Veldrid, but want to support earlier GL versions or immediate mode, you're out of luck, as far as I know.

The minimum GL version also gets bumped up a bit if you use [Veldrid.SPIRV](https://github.com/mellinoe/veldrid-spirv), a companion library that allows writing Vulkan-flavored GLSL that cross compiles to all Veldrid's supported backends. It only supports GLSL version 3.3 and newer, as far as I can tell. I've successfully used [glslValidator](https://github.com/KhronosGroup/glslang) (or [spirv-cross](https://github.com/KhronosGroup/SPIRV-Cross), one of those) to spit out GLSL 1.3, for at least the simplistic shaders I'm using, so a build step that explicitly compiles lower-end shaders isn't out of the question entirely, it's just that Veldrid won't be able to use them. I don't imagine support for any legacy versions is in the cards, frankly.

There are no doubt other wrinkles that will come up, some of which I've touched on in the Eto.Veldrid readme, some in code comments, and surely others I'm not even aware of, but that's what I can recall off the top of my head.

I also feel I'd be neglectful if I didn't at least mention [my own etoViewport fork](https://github.com/ItEndsWithTens/etoViewport/commits/arbatel); I put it together to target a custom OpenTK that supported RenderDoc ([I almost immediately delisted said OpenTK from NuGet, however](https://github.com/opentk/opentk/pull/904), so please ignore that), but it has a few other changes I didn't want to keep secret. Reviewing them as I finalize this post I realize they're more useful for my needs than anyone else's, but it'd be selfish to keep quiet about it all. Open source, and all.

WHEW. I'm done for now. I hope some of that info's useful, but I'm here for questions if I can help with anything else.

**Comment by cwensley** [comment]
All of this (should) be done now, other than creating an implementation for the Eto.Gtk platform.  See #30.
