### ISSUE TITLE
The 'report abuse' link is showing as http://localhost in the nuget package manager.

### ISSUE THREAD

**Issue by philstopford** [philstopford/etoViewport#31]
No text.

**Comment by cwensley** [comment]
Hm, I'm not seeing this issue.  Looking at the package manager I see this when searching on nuget.org:
<img width="328" alt="Screen Shot 2019-06-13 at 9 52 47 AM" src="https://user-images.githubusercontent.com/367446/59451765-0f83a100-8dc1-11e9-95b8-58e4d9f8c6da.png">

It could be because you've installed the nuget packages from a local source?  This isn't coded into the nupkg at all so (afaik) it comes from wherever you've installed it from.

**Comment by philstopford** [comment]
I'm seeing it in the CI builds : 

![image](https://user-images.githubusercontent.com/1983851/59452147-15867b80-8ddb-11e9-87ba-48d080b99414.png)

**Comment by philstopford** [comment]
If I don't look at the myget.org source, but just nuget.org, the abuse URL is correct.

**Comment by cwensley** [comment]
Ah, that's a setting on myget that I have to set.  Thanks for pointing it out!

I've set it to https://github.com/picoe/Eto (pointing to the GitHub repo appears to be the general practice) as it appears to only allow a single url for each package source.  I could create a separate package source specific to Eto.OpenTK, but that would be more onerous.

I'm hoping to switch to Github's package registry when it becomes generally available which should help with that.

I'm not sure how long it'll take for the myget settings to apply, but it should hopefully be updated now.

**Comment by cwensley** [comment]
I think this should be fixed.  Let me know if it's still showing up incorrectly.
