### ISSUE TITLE
Mac : breaks with OpenTK.Next 1.2 or OpenTK

### ISSUE THREAD

**Issue by philstopford** [philstopford/etoViewport#6]
Silently fails to complete the launch. Cause not understood yet.

**Comment by ItEndsWithTens** [comment]
I'd been having some Mac trouble of my own with the project I'd mentioned in my previous pull request, and after realizing it was due to using OpenTK 2.0.0 while Eto.Gl was using OpenTK.Next, I thought it would be good to sit down and try to work out how to get everything running. I'm not all the way there yet, but I've made some progress you might be interested in: https://github.com/ItEndsWithTens/etoViewport/tree/feature/upgrade_opentk

I know I'm new around these parts, so please accept my apologies if I'm stepping on anyone's toes with this, but I didn't see any existing branches for a 1.1->2.0 upgrade.

It's still not finished, mind you. Running either the .Mac or .XamMac executables from within Xamarin Studio, I get an exception, "_createMenuRef called with existing principal MenuRef already associated". I haven't yet found a solution for that, I'm sorry to say, but clicking Continue will let the program execute seemingly as normal, displaying the control with grid lines and letting you drag the camera, so the basic function is there at least. I believe it's related to OpenTK, and there are only two places I can see where the toolkit does any creation or modification of Mac menus: [NSApplication.cs](https://github.com/opentk/opentk/blob/d50c2fcea0696d3cc82aeb339e15c049405129ba/src/OpenTK/Platform/MacOS/Cocoa/NSApplication.cs#L65) and [CocoaNativeWindow.cs](https://github.com/opentk/opentk/blob/d50c2fcea0696d3cc82aeb339e15c049405129ba/src/OpenTK/Platform/MacOS/CocoaNativeWindow.cs#L841). That's as far as I've gotten with that, though.

In any event, the keys to making what progress I have were:

1.) Manually adding the OpenTK 2.0.0 reference to the base Eto.Gl project. Removing OpenTK.Next and installing the new version was apparently not enough, since despite the Package Console reporting a successful installation, the reference itself was nowhere in sight. Navigating to the file on disk, in the 2.0.0 package directory, did the trick.

2.) Adding a missing call to MakeCurrent in MacGLView8's InitGL method. WinForms and Gtk2 both do that before calling the graphics context's LoadAll, and it turned out to be necessary for the Mac platform to follow suit when using OpenTK 2.0.0.

3.) Hand editing the Eto.Gl.XamMac and TestEtoGl.XamMac .csproj files, updating the custom target that strips out the Xamarin.Mac version of OpenTK to replace it with the NuGet package version. This still doesn't address the inconvenience of Xamarin Studio giving you error squiggles, and lacking Intellisense for things like OpenTK.Input (not implemented by Xamarin's version of the toolkit), but the project will at least compile.

As you can see, the result isn't quite ready for primetime, but it's further than I'd gotten before, and I thought you might get some ideas from it, if nothing else.

**Comment by philstopford** [comment]
The issue with OpenTK not appearing as a reference seems to come from the PCL project type. Locally, I've modified them to no longer be PCL projects and then the reference to OpenTK shows up when adding the newer versions.

I should really have pushed those projects back to the repository here, but got swamped. I'll try and get that sorted out this evening.

I've also seen that exception being raised regarding the menu, but haven't dug in to find out why it's happening. I had in mind it was probably harmless and thought of just discarding the exception, if there's a way to do so.

**Comment by ItEndsWithTens** [comment]
Just getting back to this after a bit of a break, and it looks like [this bit in OpenTK's NSApplication.cs](https://github.com/opentk/opentk/blob/d50c2fcea0696d3cc82aeb339e15c049405129ba/src/OpenTK/Platform/MacOS/Cocoa/NSApplication.cs#L83) might be related to the _createMenuRef issue. The accompanying comment echoes what I've read elsewhere about the cause of this, that being an extra call to finishLaunching.

I don't know what to do about it, unfortunately. Honestly I'm not even sure why their NSApplication class is coming into play, trying to create an application, register a Quit handler, any of that. Eto takes care of those things, I'd assume, but calling OpenTK.Toolkit.Init as the very first line in my application's Main method doesn't alleviate the _createMenuRef crash. Is there some other way of attaching OpenTK to an existing application, I wonder? I have zero experience with the toolkit, and the current lack of website and/or documentation adds a bit of a learning curve.

**Comment by philstopford** [comment]
I think this is resolved - the base implementation was moved to use a newer OpenTK release
